set(SDKCONFIG_DEFAULTS
    ${SDKCONFIG_DEFAULTS}
    boards/sdkconfig.minimal
    boards/sdkconfig.ota.bp4mb.prod
)

list(APPEND MICROPY_DEF_BOARD
    MICROPY_HW_MCU_NAME="ESP32C3-OTA-BP-PROD"
    MICROPY_OPT_COMPUTED_GOTO=0
    MICROPY_PY_NETWORK_LAN=0
    MICROPY_PY_BLUETOOTH=0
    MICROPY_PY_WEBSOCKET=0
    MICROPY_PY_WEBREPL=0
    MICROPY_PY_MACHINE_I2S=0
    MICROPY_PY_OPENAMP=0
    MICROPY_PY_LWIP=0
    MICROPY_PY_FRAMEBUF=0
)
