set(SDKCONFIG_DEFAULTS
    boards/sdkconfig.base
    ${SDKCONFIG_IDF_VERSION_SPECIFIC}
)

if(MICROPY_BOARD_VARIANT STREQUAL "D2WD")
    set(SDKCONFIG_DEFAULTS
        ${SDKCONFIG_DEFAULTS}
        boards/ESP32_GENERIC/sdkconfig.d2wd
    )

    list(APPEND MICROPY_DEF_BOARD
        MICROPY_HW_MCU_NAME="ESP32-D2WD"
        # Disable some options to reduce firmware size.
        MICROPY_OPT_COMPUTED_GOTO=0
        MICROPY_PY_NETWORK_LAN=0
    )
endif()

if(MICROPY_BOARD_VARIANT STREQUAL "OTA")
    set(SDKCONFIG_DEFAULTS
        ${SDKCONFIG_DEFAULTS}
        boards/ESP32_GENERIC/sdkconfig.ota
    )

    list(APPEND MICROPY_DEF_BOARD
        MICROPY_HW_BOARD_NAME="Generic ESP32 module with OTA"
    )
endif()

if(MICROPY_BOARD_VARIANT STREQUAL "SPIRAM")
    set(SDKCONFIG_DEFAULTS
        ${SDKCONFIG_DEFAULTS}
        boards/sdkconfig.spiram
    )

    list(APPEND MICROPY_DEF_BOARD
        MICROPY_HW_BOARD_NAME="Generic ESP32 module with SPIRAM"
    )
endif()

if(MICROPY_BOARD_VARIANT STREQUAL "UNICORE")
    set(SDKCONFIG_DEFAULTS
        ${SDKCONFIG_DEFAULTS}
        boards/ESP32_GENERIC/sdkconfig.unicore
    )

    list(APPEND MICROPY_DEF_BOARD
        MICROPY_HW_MCU_NAME="ESP32-UNICORE"
    )
endif()

if(MICROPY_BOARD_VARIANT STREQUAL "BP_DEV_4MB")
    set(SDKCONFIG_DEFAULTS
        ${SDKCONFIG_DEFAULTS}
        boards/sdkconfig.bp4mb.dev
    )

    list(APPEND MICROPY_DEF_BOARD
        MICROPY_HW_MCU_NAME="ESP32-BP-DEV"
    )
endif()

if(MICROPY_BOARD_VARIANT STREQUAL "BP_PROD_4MB")
    set(SDKCONFIG_DEFAULTS
        ${SDKCONFIG_DEFAULTS}
        boards/sdkconfig.bp4mb.prod
    )

    list(APPEND MICROPY_DEF_BOARD
        MICROPY_HW_MCU_NAME="ESP32-BP-PROD"
    )
endif()

if(MICROPY_BOARD_VARIANT STREQUAL "OTA_BP_DEV_4MB")
    set(SDKCONFIG_DEFAULTS
        ${SDKCONFIG_DEFAULTS}
	boards/sdkconfig.minimal
        boards/sdkconfig.ota.bp4mb.dev
    )

    list(APPEND MICROPY_DEF_BOARD
        MICROPY_HW_MCU_NAME="ESP32-OTA-BP-DEV"
        MICROPY_OPT_COMPUTED_GOTO=0
        MICROPY_PY_NETWORK_LAN=0
        MICROPY_PY_BLUETOOTH=0
        MICROPY_PY_WEBSOCKET=0
        MICROPY_PY_WEBREPL=0
        MICROPY_PY_MACHINE_I2S=0
        MICROPY_PY_OPENAMP=0
        MICROPY_PY_LWIP=0
        MICROPY_PY_FRAMEBUF=0
    )
endif()

if(MICROPY_BOARD_VARIANT STREQUAL "OTA_BP_PROD_4MB")
    set(SDKCONFIG_DEFAULTS
        ${SDKCONFIG_DEFAULTS}
	boards/sdkconfig.minimal
        boards/sdkconfig.ota.bp4mb.prod
    )

    list(APPEND MICROPY_DEF_BOARD
        MICROPY_HW_MCU_NAME="ESP32-OTA-BP-PROD"
        MICROPY_OPT_COMPUTED_GOTO=0
        MICROPY_PY_NETWORK_LAN=0
        MICROPY_PY_BLUETOOTH=0
        MICROPY_PY_SSL=0
        MICROPY_SSL_MBEDTLS=0
        MICROPY_PY_CRYPTOLIB=0
        MICROPY_PY_HASHLIB=0
        MICROPY_PY_WEBSOCKET=0
        MICROPY_PY_WEBREPL=0
        MICROPY_PY_MACHINE_I2S=0
        MICROPY_PY_OPENAMP=0
        MICROPY_PY_LWIP=0
        MICROPY_PY_FRAMEBUF=0
    )
endif()
