name: Build control unit firmware

on:
  push:
    tags:
      - mp-v*

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: "ESP32_GENERIC"
            board-variant: "OTA_BP_DEV_4MB"
            output-name: "esp32"
          - board: "ESP32_GENERIC_C3"
            board-variant: "OTA_BP_DEV_4MB"
            output-name: "esp32c3"
          - board: "ESP32_GENERIC_S3"
            board-variant: "OTA_BP_DEV_8MB"
            output-name: "esp32s3"
    env:
      GH_TOKEN: ${{ secrets.AGROTURE_GA_PAT }}

    steps:
      - id: build
        uses: agroture/mp-esp32-build@v1.0
        with:
          idf-ref: ${{ vars.IDF_REF }}
          mp-ref: ${{ github.event.ref }}
          agroture-pat: ${{ secrets.AGROTURE_GA_PAT }}
          board: ${{ matrix.board }}
          board-variant: ${{ matrix.board-variant }}
          output-path: ${{ github.workspace }}/${{ matrix.output-name }}.bundle
          cache-idf: false
          cache-micropython: false

      - name: Upload to release
        run: |
          readarray -d "/" -t tparts <<< "${{ github.event.ref }}/"
          gh release upload "${tparts[2]}" ${{ github.workspace }}/${{ matrix.output-name }}.bundle --repo agroture/micropython
          
          openssl dgst -sha3-512 -binary -out ${{ github.workspace }}/${{ matrix.output-name }}.bundle.dgst ${{ github.workspace }}/${{ matrix.output-name }}.bundle
          gh release upload "${tparts[2]}" ${{ github.workspace }}/${{ matrix.output-name }}.bundle.dgst --repo agroture/micropython
